const robots = [
  {
    id: 1,
    name: "Albert Einstein",
    username: "time is a relative thing",
    email: "Albert.Einstein@gmail.com",
  },
  {
    id: 2,
    name: "Marie Curie",
    username: "radioactive brilliance",
    email: "Marie.Curie@gmail.com",
  },
  {
    id: 3,
    name: "Isaac Newton",
    username: "gravity genius",
    email: "Isaac.Newton@gmail.com",
  },
  {
    id: 4,
    name: "Charles Darwin",
    username: "evolution explorer",
    email: "Charles.Darwin@gmail.com",
  },
  {
    id: 5,
    name: "Nikola Tesla",
    username: "electric visionary",
    email: "Nikola.Tesla@gmail.com",
  },
  {
    id: 6,
    name: "Galileo Galilei",
    username: "father of astronomy",
    email: "Galileo.Galilei@gmail.com",
  },
  {
    id: 7,
    name: "Stephen Hawking",
    username: "black hole theorist",
    email: "Stephen.Hawking@gmail.com",
  },
  {
    id: 8,
    name: "Ada Lovelace",
    username: "mother of computing",
    email: "Ada.Lovelace@gmail.com",
  },
  {
    id: 9,
    name: "Rosalind Franklin",
    username: "DNA pioneer",
    email: "Rosalind.Franklin@gmail.com",
  },
  {
    id: 10,
    name: "Carl Sagan",
    username: "cosmic communicator",
    email: "Carl.Sagan@gmail.com",
  },
  {
    id: 11,
    name: "Richard Feynman",
    username: "quantum joker",
    email: "Richard.Feynman@gmail.com",
  },
  {
    id: 12,
    name: "Johannes Kepler",
    username: "celestial mathematician",
    email: "Johannes.Kepler@gmail.com",
  },
  {
    id: 13,
    name: "Dmitri Mendeleev",
    username: "periodic planner",
    email: "Dmitri.Mendeleev@gmail.com",
  },
  {
    id: 14,
    name: "Barbara McClintock",
    username: "genetic trailblazer",
    email: "Barbara.McClintock@gmail.com",
  },
  {
    id: 15,
    name: "Max Planck",
    username: "quantum pioneer",
    email: "Max.Planck@gmail.com",
  },
  {
    id: 16,
    name: "Louis Pasteur",
    username: "microbial master",
    email: "Louis.Pasteur@gmail.com",
  },
  {
    id: 17,
    name: "Gregor Mendel",
    username: "father of genetics",
    email: "Gregor.Mendel@gmail.com",
  },
  {
    id: 18,
    name: "Niels Bohr",
    username: "atomic architect",
    email: "Niels.Bohr@gmail.com",
  },
  {
    id: 19,
    name: "James Clerk Maxwell",
    username: "electromagnetic mind",
    email: "James.Maxwell@gmail.com",
  },
  {
    id: 20,
    name: "Rachel Carson",
    username: "environmental advocate",
    email: "Rachel.Carson@gmail.com",
  },
  {
    id: 21,
    name: "Alan Turing",
    username: "codebreaker",
    email: "Alan.Turing@gmail.com",
  },
  {
    id: 22,
    name: "Erwin Schrödinger",
    username: "quantum cat lover",
    email: "Erwin.Schrodinger@gmail.com",
  },
  {
    id: 23,
    name: "Blaise Pascal",
    username: "mathematical philosopher",
    email: "Blaise.Pascal@gmail.com",
  },
  {
    id: 24,
    name: "Michael Faraday",
    username: "electromagnetic wizard",
    email: "Michael.Faraday@gmail.com",
  },
  {
    id: 25,
    name: "Chien-Shiung Wu",
    username: "physics innovator",
    email: "ChienShiung.Wu@gmail.com",
  },
  {
    id: 26,
    name: "Henry Cavendish",
    username: "hydrogen discoverer",
    email: "Henry.Cavendish@gmail.com",
  },
  {
    id: 27,
    name: "Antoine Lavoisier",
    username: "father of chemistry",
    email: "Antoine.Lavoisier@gmail.com",
  },
  {
    id: 28,
    name: "Jane Goodall",
    username: "primate pioneer",
    email: "Jane.Goodall@gmail.com",
  },
  {
    id: 29,
    name: "Alfred Wegener",
    username: "continental drift theorist",
    email: "Alfred.Wegener@gmail.com",
  },
  {
    id: 30,
    name: "Gregor Mendel",
    username: "genetic father",
    email: "Gregor.Mendel@gmail.com",
  },
  {
    id: 31,
    name: "Richard Dawkins",
    username: "evolutionary biologist",
    email: "Richard.Dawkins@gmail.com",
  },
  {
    id: 32,
    name: "Louis Leakey",
    username: "human origins expert",
    email: "Louis.Leakey@gmail.com",
  },
  {
    id: 33,
    name: "Srinivasa Ramanujan",
    username: "mathematical prodigy",
    email: "Srinivasa.Ramanujan@gmail.com",
  },
  {
    id: 34,
    name: "Maxwell Boden",
    username: "chemistry aficionado",
    email: "Maxwell.Boden@gmail.com",
  },
  {
    id: 35,
    name: "Mae Jemison",
    username: "space adventurer",
    email: "Mae.Jemison@gmail.com",
  },
  {
    id: 36,
    name: "John von Neumann",
    username: "mathematics genius",
    email: "John.von.Neumann@gmail.com",
  },
  {
    id: 37,
    name: "Benjamin Franklin",
    username: "electrical inventor",
    email: "Benjamin.Franklin@gmail.com",
  },
  {
    id: 38,
    name: "John Dalton",
    username: "atomic theorist",
    email: "John.Dalton@gmail.com",
  },
  {
    id: 39,
    name: "Francis Crick",
    username: "double helix discoverer",
    email: "Francis.Crick@gmail.com",
  },
  {
    id: 40,
    name: "Maurice Wilkins",
    username: "X-ray expert",
    email: "Maurice.Wilkins@gmail.com",
  },
  {
    id: 41,
    name: "Robert Hooke",
    username: "cell theory co-founder",
    email: "Robert.Hooke@gmail.com",
  },
  {
    id: 42,
    name: "Dorothy Crowfoot Hodgkin",
    username: "protein crystallographer",
    email: "Dorothy.Hodgkin@gmail.com",
  },
  {
    id: 43,
    name: "James Watson",
    username: "DNA discoverer",
    email: "James.Watson@gmail.com",
  },
  {
    id: 44,
    name: "Catherine Johnson",
    username: "space math genius",
    email: "Catherine.Johnson@gmail.com",
  },
  {
    id: 45,
    name: "Hedy Lamarr",
    username: "technology innovator",
    email: "Hedy.Lamarr@gmail.com",
  },
  {
    id: 46,
    name: "Barbara McClintock",
    username: "genetics pioneer",
    email: "Barbara.McClintock@gmail.com",
  },
  {
    id: 47,
    name: "Neil deGrasse Tyson",
    username: "cosmic mentor",
    email: "Neil.deGrasse.Tyson@gmail.com",
  },
  {
    id: 48,
    name: "Murray Gell-Mann",
    username: "quantum physicist",
    email: "Murray.Gell-Mann@gmail.com",
  },
  {
    id: 49,
    name: "Craig Venter",
    username: "genomics guru",
    email: "Craig.Venter@gmail.com",
  },
  {
    id: 50,
    name: "Steven Pinker",
    username: "evolutionary psychologist",
    email: "Steven.Pinker@gmail.com",
  },
  {
    id: 51,
    name: "Jane Goodall",
    username: "primate researcher",
    email: "Jane.Goodall@gmail.com",
  },
  {
    id: 52,
    name: "Baruch S. Blumberg",
    username: "medical researcher",
    email: "Baruch.Blumberg@gmail.com",
  },
  {
    id: 53,
    name: "Robert Boyle",
    username: "gas law discoverer",
    email: "Robert.Boyle@gmail.com",
  },
  {
    id: 54,
    name: "Galileo Galilei",
    username: "astronomy innovator",
    email: "Galileo.Galilei@gmail.com",
  },
  {
    id: 55,
    name: "Gerty Cori",
    username: "biochemist",
    email: "Gerty.Cori@gmail.com",
  },
  {
    id: 56,
    name: "Rita Levi-Montalcini",
    username: "neuroscientist",
    email: "Rita.LeviMontalcini@gmail.com",
  },
  {
    id: 57,
    name: "Niels Bohr",
    username: "atomic model creator",
    email: "Niels.Bohr@gmail.com",
  },
  {
    id: 58,
    name: "Paul Dirac",
    username: "mathematical physicist",
    email: "Paul.Dirac@gmail.com",
  },
  {
    id: 59,
    name: "Marie Maynard Daly",
    username: "biochemist",
    email: "Marie.Maynard.Daly@gmail.com",
  },
  {
    id: 60,
    name: "Katherine Johnson",
    username: "space mathematician",
    email: "Katherine.Johnson@gmail.com",
  },
  {
    id: 61,
    name: "Clint Eastwood",
    username: "scientific sculptor",
    email: "Clint.Eastwood@gmail.com",
  },
  {
    id: 62,
    name: "Caroline Herschel",
    username: "astronomy assistant",
    email: "Caroline.Herschel@gmail.com",
  },
  {
    id: 63,
    name: "Lise Meitner",
    username: "atomic fission co-discoverer",
    email: "Lise.Meitner@gmail.com",
  },
  {
    id: 64,
    name: "J.J. Thomson",
    username: "electron discoverer",
    email: "JJ.Thomson@gmail.com",
  },
  {
    id: 65,
    name: "Thomas Edison",
    username: "light bulb inventor",
    email: "Thomas.Edison@gmail.com",
  },
  {
    id: 66,
    name: "Emilie du Châtelet",
    username: "philosopher physicist",
    email: "Emilie.du.Chatelet@gmail.com",
  },
  {
    id: 67,
    name: "Henrietta Swan Leavitt",
    username: "star distance pioneer",
    email: "Henrietta.Leavitt@gmail.com",
  },
  {
    id: 68,
    name: "James Clerk Maxwell",
    username: "electromagnetic genius",
    email: "James.Clerk.Maxwell@gmail.com",
  },
  {
    id: 69,
    name: "Gustave Eiffel",
    username: "structural engineer",
    email: "Gustave.Eiffel@gmail.com",
  },
  {
    id: 70,
    name: "Mendelian Geneticist",
    username: "genetic theory pioneer",
    email: "Mendel.Geneticist@gmail.com",
  },
  {
    id: 71,
    name: "Erwin Schrödinger",
    username: "quantum cat lover",
    email: "Erwin.Schrodinger@gmail.com",
  },
  {
    id: 72,
    name: "Karl Popper",
    username: "science philosopher",
    email: "Karl.Popper@gmail.com",
  },
  {
    id: 73,
    name: "Henri Poincaré",
    username: "mathematician",
    email: "Henri.Poincare@gmail.com",
  },
  {
    id: 74,
    name: "Brennan Johnson",
    username: "cell biologist",
    email: "Brennan.Johnson@gmail.com",
  },
  {
    id: 75,
    name: "Charles Lyell",
    username: "geology expert",
    email: "Charles.Lyell@gmail.com",
  },
  {
    id: 76,
    name: "Sir Michael Atiyah",
    username: "mathematician",
    email: "Michael.Atiyah@gmail.com",
  },
  {
    id: 77,
    name: "André-Marie Ampère",
    username: "electromagnetic pioneer",
    email: "AndreMarie.Ampere@gmail.com",
  },
  {
    id: 78,
    name: "Clyde Tombaugh",
    username: "Pluto discoverer",
    email: "Clyde.Tombaugh@gmail.com",
  },
  {
    id: 79,
    name: "Richard Dawkins",
    username: "evolutionary biologist",
    email: "Richard.Dawkins@gmail.com",
  },
  {
    id: 80,
    name: "Hans Albrecht Bethe",
    username: "nuclear physicist",
    email: "Hans.Bethe@gmail.com",
  },
  {
    id: 81,
    name: "Francois Barre-Sinoussi",
    username: "HIV researcher",
    email: "Francois.Barre-Sinoussi@gmail.com",
  },
  {
    id: 82,
    name: "Ernst Rutherford",
    username: "atomic scientist",
    email: "Ernst.Rutherford@gmail.com",
  },
  {
    id: 83,
    name: "Sally Ride",
    username: "astronaut",
    email: "Sally.Ride@gmail.com",
  },
  {
    id: 84,
    name: "Valentina Tereshkova",
    username: "first woman in space",
    email: "Valentina.Tereshkova@gmail.com",
  },
  {
    id: 85,
    name: "Emil Fischer",
    username: "chemist",
    email: "Emil.Fischer@gmail.com",
  },
  {
    id: 86,
    name: "Rosalind Franklin",
    username: "DNA scientist",
    email: "Rosalind.Franklin@gmail.com",
  },
  {
    id: 87,
    name: "Franklin Chang-Diaz",
    username: "NASA engineer",
    email: "Franklin.Chang-Diaz@gmail.com",
  },
  {
    id: 88,
    name: "Margo Seltzer",
    username: "database expert",
    email: "Margo.Seltzer@gmail.com",
  },
  {
    id: 89,
    name: "Gertrude Elion",
    username: "pharmacologist",
    email: "Gertrude.Elion@gmail.com",
  },
  {
    id: 90,
    name: "Louis Armstrong",
    username: "space science",
    email: "Louis.Armstrong@gmail.com",
  },
  {
    id: 91,
    name: "Jane Goodall",
    username: "wildlife researcher",
    email: "Jane.Goodall@gmail.com",
  },
  {
    id: 92,
    name: "Daniel Bernoulli",
    username: "fluid dynamics expert",
    email: "Daniel.Bernoulli@gmail.com",
  },
  {
    id: 93,
    name: "Ferdinand von Zeppelin",
    username: "airship inventor",
    email: "Ferdinand.Zeppelin@gmail.com",
  },
  {
    id: 94,
    name: "Joseph Priestley",
    username: "discovery of oxygen",
    email: "Joseph.Priestley@gmail.com",
  },
  {
    id: 95,
    name: "Fritz Haber",
    username: "chemical engineer",
    email: "Fritz.Haber@gmail.com",
  },
  {
    id: 96,
    name: "Gertrude B. Elion",
    username: "drug development",
    email: "Gertrude.Elion@gmail.com",
  },
  {
    id: 97,
    name: "Abraham Flexner",
    username: "medical reformer",
    email: "Abraham.Flexner@gmail.com",
  },
  {
    id: 98,
    name: "Diana Spencer",
    username: "family values",
    email: "Diana.Spencer@gmail.com",
  },
  {
    id: 99,
    name: "Jules Verne",
    username: "visionary",
    email: "Jules.Verne@gmail.com",
  },
  {
    id: 100,
    name: "Robert Koch",
    username: "germ theory",
    email: "Robert.Koch@gmail.com",
  },
];

export default robots;
